apiVersion: v1
kind: Service
metadata:
  name: nodejsapp-client-service
  namespace: nodejsapp-prod
spec:
  selector:
    app: nodejsapp
    tier: client
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
