name: CD

on: 
  push:
    paths: 
      - 'nodejs_app/db/**'
      - 'nodejs_app/client/**'
    branches: 
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to dockerhub
        id: login-dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push client image to dockerhub
        env:
          REGISTRY: ${{ steps.login-dockerhub.outputs.registry }}
          REPOSITORY: prod-nodejsapp-client
          IMAGE_TAG: latest
        run: |
          cd nodejs_app/client/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$REPOSITORY:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/$REPOSITORY:$IMAGE_TAG
      - name: Build and push db image to dockerhub
        env:
          REGISTRY: ${{ steps.login-dockerhub.outputs.registry }}
          REPOSITORY: prod-nodejsapp-db
          IMAGE_TAG: latest
        run: |
          cd nodejs_app/db/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$REPOSITORY:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/$REPOSITORY:$IMAGE_TAG
      - name: Logout of Dockerhub
        if: always()
        run: docker logout ${{ steps.login-dockerhub.outputs.registry }}
